# Generated by Django 4.2.16 on 2026-10-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("partenaires", "0002_ausbau_kontakte_logo_dokumente_angebote"),
        ("finances", "0005_gesamtbudget_projektbudget"),
    ]

    operations = [
        migrations.AddField(
            model_name="depense",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ausgaben",
                to="partenaires.partner",
            ),
        ),
    ]
