# Generated by Django 4.2.16 on 2026-09-11 23:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membres", "0003_membre_pays_alter_membre_adresse_de_and_more"),
        ("cotisations", "0004_configurationrelance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Covoiturage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("depart", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("date_trajet", models.DateField()),
                ("heure_trajet", models.TimeField()),
                (
                    "places_disponibles",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "prix_par_place",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vide = trajet gratuit.",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("vehicule", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conducteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trajets_proposes",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Covoiturage",
                "verbose_name_plural": "Covoiturages",
                "db_table": "evenements_covoiturages",
                "ordering": ["date_trajet", "heure_trajet"],
            },
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("deplacement", "Déplacement"),
                            ("fete", "Fête / Rassemblement"),
                            ("conference", "AMA / Conférence"),
                            ("tournoi", "Tournoi"),
                            ("ag", "Assemblée Générale"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("date_evenement", models.DateField()),
                ("heure", models.TimeField(blank=True, null=True)),
                (
                    "lieu",
                    models.CharField(
                        help_text="Stade/salle, ville, adresse complète.", max_length=255
                    ),
                ),
                ("point_rdv", models.CharField(blank=True, max_length=255)),
                (
                    "places_max",
                    models.PositiveIntegerField(
                        blank=True, help_text="Vide = pas de limite de capacité.", null=True
                    ),
                ),
                ("gratuit", models.BooleanField(default=False)),
                (
                    "cout",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Ignoré (toujours 0) si gratuit=True — voir Evenement.save().",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("publie", "Publié"),
                            ("annule", "Annulé"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Traçabilité — SCD §7.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evenements_crees",
                        to="membres.membre",
                    ),
                ),
                (
                    "organisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements_organises",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "db_table": "evenements",
                "ordering": ["date_evenement", "heure"],
            },
        ),
        migrations.CreateModel(
            name="ReservationCovoiturage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "places_reservees",
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("point_prise_en_charge", models.CharField(blank=True, max_length=255)),
                (
                    "statut",
                    models.CharField(
                        choices=[("confirmee", "Confirmée"), ("annulee", "Annulée")],
                        default="confirmee",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations_covoiturage",
                        to="membres.membre",
                    ),
                ),
                (
                    "trajet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="evenements.covoiturage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation covoiturage",
                "verbose_name_plural": "Réservations covoiturage",
                "db_table": "evenements_reservations_covoiturage",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "places",
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "regime_alimentaire",
                    models.CharField(
                        choices=[
                            ("aucun", "Aucun"),
                            ("halal", "Halal"),
                            ("vegetarien", "Végétarien"),
                        ],
                        default="aucun",
                        max_length=20,
                    ),
                ),
                ("remarques", models.TextField(blank=True)),
                (
                    "montant_paye",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Recalculé côté serveur = evenement.cout * places (CLAUDE.md §8).",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente_paiement", "En attente de paiement"),
                            ("confirmee", "Confirmée"),
                            ("annulee", "Annulée"),
                        ],
                        default="confirmee",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cotisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Écriture de paiement liée, une fois l'inscription payante réglée.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inscription_evenement",
                        to="cotisations.cotisation",
                    ),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="evenements.evenement",
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscriptions_evenements",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
                "db_table": "evenements_inscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="covoiturage",
            name="evenement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trajets_covoiturage",
                to="evenements.evenement",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservationcovoiturage",
            constraint=models.UniqueConstraint(
                fields=("trajet", "membre"), name="une_seule_reservation_par_membre_trajet"
            ),
        ),
        migrations.AddIndex(
            model_name="inscription",
            index=models.Index(
                fields=["evenement", "statut"], name="evenements__eveneme_6d949b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inscription",
            constraint=models.UniqueConstraint(
                fields=("evenement", "membre"), name="une_seule_inscription_par_membre_evenement"
            ),
        ),
        migrations.AddIndex(
            model_name="evenement",
            index=models.Index(
                fields=["statut", "date_evenement"], name="evenements_statut_461f39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evenement",
            index=models.Index(fields=["type_evenement"], name="evenements_type_ev_e5ad76_idx"),
        ),
        migrations.AddIndex(
            model_name="covoiturage",
            index=models.Index(fields=["date_trajet"], name="evenements__date_tr_44f7cd_idx"),
        ),
    ]
