# Generated by Django 4.2.16 on 2026-09-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0003_backfill_cotisation_inscriptions_en_attente"),
    ]

    operations = [
        migrations.AddField(
            model_name="covoiturage",
            name="lieu_rendez_vous",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Point de rendez-vous fixé par le conducteur pour l'ensemble du trajet "
                    "(« Treffpunkt », signalé par un utilisateur — 2026-09-25) — distinct du "
                    "point de prise en charge propre à chaque passager (voir "
                    "ReservationCovoiturage.point_prise_en_charge)."
                ),
                max_length=255,
            ),
        ),
    ]
