# Generated by Django 4.2.16 on 2026-09-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0004_ajoute_lieu_rendez_vous_covoiturage"),
    ]

    operations = [
        migrations.AddField(
            model_name="covoiturage",
            name="remarques",
            field=models.TextField(
                blank=True,
                help_text="Description / remarque libre laissée par le conducteur à la création du trajet (demande utilisateur 2026-09-25, « Beschreibung / Anmerkung erfassen ») — ex. arrêts prévus en route, préférences (non-fumeur, musique), bagages acceptés. Distincte de lieu_rendez_vous (point de RDV structuré) : texte libre affiché tel quel aux passagers potentiels avant qu'ils ne rejoignent le trajet.",
            ),
        ),
    ]
