# Generated by Django 4.2.16 on 2026-09-25 13:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0005_ajoute_remarques_covoiturage"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="accompagnants_payants",
            field=models.BooleanField(
                default=False,
                help_text="Si activé, un accompagnant inscrit avec un membre est facturé au tarif adulte/enfant ci-dessous. Sinon toujours gratuit, quels que soient ces tarifs.",
            ),
        ),
        migrations.AddField(
            model_name="evenement",
            name="age_limite_accompagnant_enfant",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Âge strictement inférieur à cette limite = tarif enfant (purement indicatif côté formulaire d'inscription, qui ne demande que des décomptes adulte/enfant, jamais l'âge exact de chaque accompagnant).",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="evenement",
            name="prix_accompagnant_adulte",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Ignoré si accompagnants_payants=False.",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="evenement",
            name="prix_accompagnant_enfant",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Ignoré si accompagnants_payants=False.",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="nombre_accompagnants_adultes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inscription",
            name="nombre_accompagnants_enfants",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="montant_paye",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Recalculé côté serveur = evenement.cout * places + montant_accompagnants (CLAUDE.md §8).",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
