# Generated by Django 4.2.16 on 2026-09-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0006_evenement_accompagnants_payants_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="visible_public",
            field=models.BooleanField(
                default=False,
                help_text="Si activé, cet événement (une fois publié) est aussi visible sur la page d'accueil publique, pour les visiteurs non connectés et les non-membres.",
            ),
        ),
    ]
