# Generated by Django 4.2.16 on 2026-09-27 09:20

import apps.evenements.models
import apps.evenements.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0007_evenement_visible_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="covoiturage",
            name="lieu_rendez_vous_maps_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="evenement",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image affichée sur la kachel de l'événement (page d'accueil publique).",
                null=True,
                storage=apps.evenements.storage.EvenementsStorage(),
                upload_to=apps.evenements.models.evenement_image_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="evenement",
            name="lieu_maps_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
