# Generated by Django 4.2.16 on 2026-10-05 17:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0008_covoiturage_lieu_rendez_vous_maps_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="cout_non_membre",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tarif non-membre. Vide = identique au tarif membre (cout).",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
