# Generated by Django 4.2.16 on 2026-09-12 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("bienvenue", "Bienvenue"),
                            ("paiement_confirme", "Paiement confirmé"),
                            ("relance_cotisation", "Relance cotisation"),
                            ("evenement_invitation", "Invitation à un événement"),
                            ("evenement_rappel", "Rappel d'événement"),
                            ("boutique_commande_confirmee", "Commande confirmée"),
                            ("boutique_commande_expediee", "Commande expédiée"),
                            ("vote_ouverture", "Ouverture d'un vote"),
                            ("vote_resultats", "Résultats d'un vote"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "lien",
                    models.CharField(
                        blank=True,
                        help_text="Chemin relatif frontend vers l'objet concerné (ex. /evenements/<id>).",
                        max_length=255,
                    ),
                ),
                ("lu", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["destinataire", "lu"], name="notificatio_destina_b098b5_idx"
                    )
                ],
            },
        ),
    ]
