# Generated by Django 4.2.16 on 2026-09-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_notification",
            field=models.CharField(
                choices=[
                    ("bienvenue", "Bienvenue"),
                    ("paiement_confirme", "Paiement confirmé"),
                    ("relance_cotisation", "Relance cotisation"),
                    ("evenement_invitation", "Invitation à un événement"),
                    ("evenement_rappel", "Rappel d'événement"),
                    ("boutique_commande_confirmee", "Commande confirmée"),
                    ("boutique_commande_expediee", "Commande expédiée"),
                    ("vote_ouverture", "Ouverture d'un vote"),
                    ("vote_resultats", "Résultats d'un vote"),
                    ("message_prive_recu", "Nouveau message privé"),
                    ("adhesion_campagne_publiee", "Nouvelle campagne d'adhésion"),
                    ("adhesion_justificatif_valide", "Justificatif validé"),
                    ("adhesion_justificatif_refuse", "Justificatif refusé"),
                    ("adhesion_souscription_annulee", "Souscription annulée"),
                    ("evenement_annule", "Événement annulé"),
                    ("boutique_commande_annulee", "Commande annulée"),
                    ("communaute_reponse_forum", "Nouvelle réponse sur un sujet"),
                ],
                max_length=30,
            ),
        ),
    ]
