# Generated by Django 4.2.16 on 2026-09-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0004_historique_statut_membre"),
        ("notifications", "0004_alter_notification_type_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametresNotification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email_membres", models.BooleanField(default=True, verbose_name="Membres")),
                (
                    "email_cotisations",
                    models.BooleanField(default=True, verbose_name="Cotisations"),
                ),
                ("email_adhesions", models.BooleanField(default=True, verbose_name="Adhésions")),
                ("email_evenements", models.BooleanField(default=True, verbose_name="Événements")),
                ("email_boutique", models.BooleanField(default=True, verbose_name="Boutique")),
                ("email_vote", models.BooleanField(default=True, verbose_name="Vote")),
                ("email_communaute", models.BooleanField(default=True, verbose_name="Communauté")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Administrateur App ayant modifié ce paramétrage en dernier.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres de notification",
                "verbose_name_plural": "Paramètres de notification",
                "db_table": "notifications_parametres",
            },
        ),
    ]
