# Generated by Django 4.2.16 on 2026-10-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_alter_notification_type_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_notification",
            field=models.CharField(
                choices=[
                    ("bienvenue", "Bienvenue"),
                    ("paiement_confirme", "Paiement confirmé"),
                    ("relance_cotisation", "Relance cotisation"),
                    ("evenement_invitation", "Invitation à un événement"),
                    ("evenement_rappel", "Rappel d'événement"),
                    ("boutique_commande_confirmee", "Commande confirmée"),
                    ("boutique_commande_expediee", "Commande expédiée"),
                    ("vote_ouverture", "Ouverture d'un vote"),
                    ("vote_resultats", "Résultats d'un vote"),
                    ("message_prive_recu", "Nouveau message privé"),
                    ("adhesion_campagne_publiee", "Nouvelle campagne d'adhésion"),
                    ("adhesion_justificatif_valide", "Justificatif validé"),
                    ("adhesion_justificatif_refuse", "Justificatif refusé"),
                    ("adhesion_souscription_annulee", "Souscription annulée"),
                    ("evenement_annule", "Événement annulé"),
                    ("boutique_commande_annulee", "Commande annulée"),
                    ("communaute_reponse_forum", "Nouvelle réponse sur un sujet"),
                    ("adhesion_justificatif_soumis", "Nouveau justificatif soumis"),
                    ("accounts_nouvelle_inscription", "Nouvelle inscription"),
                    ("cotisation_paiement_attente", "Paiement en attente"),
                    ("boutique_nouvelle_commande", "Nouvelle commande"),
                    ("communaute_message_groupe", "Nouveau message de groupe"),
                    ("communaute_commentaire_fil", "Nouveau commentaire"),
                    ("membre_statut_actif", "Statut de membre réactivé"),
                    ("membre_statut_inactif", "Statut de membre désactivé"),
                    ("boutique_bon_achat_actif", "Bon d'achat prêt à l'emploi"),
                    ("communaute_mention", "Vous avez été mentionné·e"),
                    ("communaute_info_importante", "Neuigkeit importante"),
                ],
                max_length=30,
            ),
        ),
    ]
