# Generated by Django 4.2.16 on 2026-10-07 07:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


KATEGORIEN = [
    ("Catering", "Restauration"),
    ("Druck & Werbung", "Impression et publicité"),
    ("Location", "Lieu / salle"),
    ("Transport & Reisen", "Transport et voyages"),
    ("Technik & Medien", "Technique et médias"),
    ("Merchandising & Textil", "Merchandising et textile"),
    ("Sponsoring", "Sponsoring"),
    ("Versicherung & Recht", "Assurance et droit"),
    ("Sonstiges", "Divers"),
]


def kategorien_anlegen(apps, schema_editor):
    kategorie = apps.get_model("partenaires", "PartnerKategorie")
    for nom, nom_fr in KATEGORIEN:
        kategorie.objects.get_or_create(nom=nom, defaults={"nom_fr": nom_fr})


def kategorien_entfernen(apps, schema_editor):
    kategorie = apps.get_model("partenaires", "PartnerKategorie")
    kategorie.objects.filter(nom__in=[nom for nom, _ in KATEGORIEN], partner__isnull=True).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boutique", "0008_produitimage"),
        ("projets", "0008_historische_beitraege"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("evenements", "0010_fin_evenement_echeance_paiement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("partner", "Business Partner"),
                            ("lieferant", "Lieferant"),
                            ("beides", "Partner & Lieferant"),
                        ],
                        default="partner",
                        max_length=10,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("aktiv", "Aktiv"),
                            ("inaktiv", "Inaktiv"),
                            ("archiviert", "Archiviert"),
                        ],
                        default="aktiv",
                        max_length=12,
                    ),
                ),
                (
                    "bevorzugt",
                    models.BooleanField(
                        default=False,
                        help_text="Bevorzugter Partner/Lieferant (in Listen hervorgehoben).",
                    ),
                ),
                ("ansprechpartner", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefon", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("adresse", models.CharField(blank=True, max_length=255)),
                ("code_postal", models.CharField(blank=True, max_length=20)),
                ("ville", models.CharField(blank=True, max_length=100)),
                ("pays", models.CharField(blank=True, default="Deutschland", max_length=100)),
                ("ust_id", models.CharField(blank=True, max_length=30, verbose_name="USt-IdNr.")),
                ("zahlungsziel_tage", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("notizen", models.TextField(blank=True, verbose_name="Interne Notizen")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Partner",
                "verbose_name_plural": "Business Partner & Lieferanten",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="PartnerKategorie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="Name (Deutsch)"),
                ),
                (
                    "nom_fr",
                    models.CharField(blank=True, max_length=100, verbose_name="Name (Französisch)"),
                ),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Partner-Kategorie",
                "verbose_name_plural": "Partner-Kategorien",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="PartnerVerknuepfung",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "rolle",
                    models.CharField(
                        choices=[
                            ("lieferant", "Lieferant"),
                            ("sponsor", "Sponsor"),
                            ("kooperation", "Kooperationspartner"),
                            ("location", "Location"),
                            ("dienstleister", "Dienstleister"),
                            ("sonstige", "Sonstige"),
                        ],
                        default="sonstige",
                        max_length=15,
                    ),
                ),
                ("notiz", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_verknuepfungen",
                        to="evenements.evenement",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verknuepfungen",
                        to="partenaires.partner",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_verknuepfungen",
                        to="boutique.produit",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_verknuepfungen",
                        to="projets.projet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerBewertung",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "qualitaet",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "preis_leistung",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "zuverlaessigkeit",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "kommunikation",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("kommentar", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bewerter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bewertungen",
                        to="partenaires.partner",
                    ),
                ),
                (
                    "verknuepfung",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bewertungen",
                        to="partenaires.partnerverknuepfung",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="partner",
            name="kategorien",
            field=models.ManyToManyField(
                blank=True, related_name="partner", to="partenaires.partnerkategorie"
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerverknuepfung",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("evenement__isnull", True),
                        ("produit__isnull", True),
                        ("projet__isnull", False),
                    ),
                    models.Q(
                        ("evenement__isnull", False),
                        ("produit__isnull", True),
                        ("projet__isnull", True),
                    ),
                    models.Q(
                        ("evenement__isnull", True),
                        ("produit__isnull", False),
                        ("projet__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="partner_verknuepfung_genau_ein_ziel",
            ),
        ),
        migrations.RunPython(kategorien_anlegen, kategorien_entfernen),
    ]
