# Generated by Django 4.2.16 on 2026-10-07 08:29

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.adhesions.storage
import apps.partenaires.models
import apps.projets.storage


def ansprechpartner_nach_kontakt(apps, schema_editor):
    """Das frühere Freitext-Feld `ansprechpartner` wird zum Hauptkontakt."""
    Partner = apps.get_model("partenaires", "Partner")
    PartnerKontakt = apps.get_model("partenaires", "PartnerKontakt")
    for partner in Partner.objects.exclude(ansprechpartner=""):
        PartnerKontakt.objects.create(
            partner=partner,
            name=partner.ansprechpartner[:200],
            hauptkontakt=True,
        )


def kontakt_nach_ansprechpartner(apps, schema_editor):
    Partner = apps.get_model("partenaires", "Partner")
    PartnerKontakt = apps.get_model("partenaires", "PartnerKontakt")
    for partner in Partner.objects.all():
        kontakt = (
            PartnerKontakt.objects.filter(partner=partner)
            .order_by("-hauptkontakt", "name")
            .first()
        )
        if kontakt:
            partner.ansprechpartner = kontakt.name[:200]
            partner.save(update_fields=["ansprechpartner"])


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0008_historische_beitraege"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("partenaires", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.projets.storage.ProjetsStorage(),
                upload_to=apps.partenaires.models.partner_logo_path,
            ),
        ),
        migrations.AddField(
            model_name="partnerverknuepfung",
            name="bewertung_erinnert",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="partnerverknuepfung",
            name="logo_anzeigen",
            field=models.BooleanField(
                default=False,
                help_text="Partner-Logo auf der Seite des Projekts / der Veranstaltung zeigen.",
            ),
        ),
        migrations.CreateModel(
            name="PartnerKontakt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("funktion", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefon", models.CharField(blank=True, max_length=50)),
                ("hauptkontakt", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kontakte",
                        to="partenaires.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ansprechperson",
                "verbose_name_plural": "Ansprechpersonen",
                "ordering": ["-hauptkontakt", "name"],
            },
        ),
        migrations.RunPython(ansprechpartner_nach_kontakt, kontakt_nach_ansprechpartner),
        migrations.RemoveField(
            model_name="partner",
            name="ansprechpartner",
        ),
        migrations.CreateModel(
            name="PartnerDokument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("vertrag", "Vertrag"),
                            ("angebot", "Angebot"),
                            ("sonstiges", "Sonstiges"),
                        ],
                        default="vertrag",
                        max_length=10,
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                (
                    "datei",
                    models.FileField(
                        storage=apps.adhesions.storage.JustificatifsStorage(),
                        upload_to=apps.partenaires.models.partner_dokument_path,
                    ),
                ),
                ("gueltig_bis", models.DateField(blank=True, null=True)),
                ("notiz", models.CharField(blank=True, max_length=300)),
                ("erinnert_60", models.BooleanField(default=False)),
                ("erinnert_14", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hochgeladen_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dokumente",
                        to="partenaires.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner-Dokument",
                "verbose_name_plural": "Partner-Dokumente",
                "ordering": ["gueltig_bis", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Angebot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("gueltig_bis", models.DateField(blank=True, null=True)),
                ("beschreibung", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offen", "Offen"),
                            ("zuschlag", "Zuschlag"),
                            ("abgelehnt", "Abgelehnt"),
                        ],
                        default="offen",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dokument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="partenaires.partnerdokument",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="angebote",
                        to="partenaires.partner",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_angebote",
                        to="projets.projet",
                    ),
                ),
            ],
            options={
                "ordering": ["betrag", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="angebot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "zuschlag")),
                fields=("projet",),
                name="angebot_ein_zuschlag_je_projekt",
            ),
        ),
    ]
