# Generated by Django 4.2.16 on 2026-10-07 11:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("evenements", "0010_fin_evenement_echeance_paiement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projets", "0008_historische_beitraege"),
        ("partenaires", "0003_planifier_erinnerungen_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="auf_startseite",
            field=models.BooleanField(
                default=False,
                help_text='Logo im Banner "Unsere Sponsoren und Business Partner" der Startseite zeigen.',
            ),
        ),
        migrations.CreateModel(
            name="PartnerEinnahme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("datum", models.DateField()),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "art",
                    models.CharField(
                        choices=[
                            ("sponsoring", "Sponsoring"),
                            ("spende", "Spende"),
                            ("sonstige", "Sonstige Einnahme"),
                        ],
                        default="sponsoring",
                        max_length=12,
                    ),
                ),
                ("bezeichnung", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="evenements.evenement",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="einnahmen",
                        to="partenaires.partner",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="projets.projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner-Einnahme",
                "verbose_name_plural": "Partner-Einnahmen",
                "ordering": ["-datum", "-created_at"],
            },
        ),
    ]
