# Generated by Django 4.2.16 on 2026-09-10 19:21

import apps.membres.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "numero_membre",
                    models.CharField(
                        editable=False,
                        help_text="Généré automatiquement : CA-<année d'adhésion>-<compteur> (voir mockup).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("prenom", models.CharField(max_length=100)),
                ("nom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField()),
                (
                    "sexe",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("homme", "Homme"),
                            ("femme", "Femme"),
                            ("non_renseigne", "Non renseigné"),
                        ],
                        default="non_renseigne",
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email de contact du membre. Dupliqué depuis le compte utilisateur si lié — renseigné indépendamment pour les fiches importées sans compte.",
                        max_length=254,
                    ),
                ),
                (
                    "telephone",
                    models.CharField(help_text="Format allemand attendu (+49…).", max_length=30),
                ),
                ("cin", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "passeport",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
                ),
                (
                    "adresse_de",
                    models.CharField(max_length=255, verbose_name="Adresse (Allemagne)"),
                ),
                ("code_postal_de", models.CharField(blank=True, max_length=10)),
                ("ville_de", models.CharField(max_length=100, verbose_name="Ville (Allemagne)")),
                (
                    "land_de",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BW", "Baden-Württemberg"),
                            ("BY", "Bayern"),
                            ("BE", "Berlin"),
                            ("BB", "Brandenburg"),
                            ("HB", "Bremen"),
                            ("HH", "Hamburg"),
                            ("HE", "Hessen"),
                            ("MV", "Mecklenburg-Vorpommern"),
                            ("NI", "Niedersachsen"),
                            ("NW", "Nordrhein-Westfalen"),
                            ("RP", "Rheinland-Pfalz"),
                            ("SL", "Saarland"),
                            ("SN", "Sachsen"),
                            ("ST", "Sachsen-Anhalt"),
                            ("SH", "Schleswig-Holstein"),
                            ("TH", "Thüringen"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "ville_origine_tn",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ville d'origine (Tunisie)"
                    ),
                ),
                (
                    "gouvernorat_tn",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Gouvernorat (Tunisie)"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("en_attente", "En attente"),
                            ("inactif", "Inactif"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_adhesion", models.DateField(default=django.utils.timezone.now)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.membres.models.membre_photo_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Compte de connexion associé. Vide pour un membre importé (RICEFW C-001) tant qu'il ne s'est pas inscrit / n'a pas été invité à créer son compte.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membre",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
                "db_table": "membres",
                "ordering": ["nom", "prenom"],
                "indexes": [
                    models.Index(fields=["statut"], name="membres_statut_c9b410_idx"),
                    models.Index(fields=["nom", "prenom"], name="membres_nom_1d6d6b_idx"),
                    models.Index(fields=["ville_de"], name="membres_ville_d_47e0ff_idx"),
                ],
            },
        ),
    ]
