# Generated by Django 4.2.16 on 2026-09-10 19:57

import apps.membres.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="date_adhesion",
            field=models.DateField(default=apps.membres.models._aujourd_hui),
        ),
    ]
