# Generated by Django 4.2.16 on 2026-09-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0002_alter_membre_date_adhesion"),
    ]

    operations = [
        migrations.AddField(
            model_name="membre",
            name="pays",
            field=models.CharField(
                choices=[
                    ("DE", "Allemagne"),
                    ("TN", "Tunisie"),
                    ("FR", "France"),
                    ("AT", "Autriche"),
                    ("CH", "Suisse"),
                    ("BE", "Belgique"),
                    ("NL", "Pays-Bas"),
                    ("IT", "Italie"),
                    ("ES", "Espagne"),
                    ("GB", "Royaume-Uni"),
                    ("XX", "Autre"),
                ],
                default="DE",
                help_text="Si différent de l'Allemagne, l'adresse allemande détaillée (rue, ville, Bundesland) n'est pas requise — seul le pays compte.",
                max_length=2,
                verbose_name="Pays de résidence",
            ),
        ),
        migrations.AlterField(
            model_name="membre",
            name="adresse_de",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresse (Allemagne)"),
        ),
        migrations.AlterField(
            model_name="membre",
            name="ville_de",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ville (Allemagne)"),
        ),
    ]
