# Generated by Django 4.2.16 on 2026-09-19, complétée manuellement (retour utilisateur du
# 2026-09-19 : "Es soll eine Historie der Mitgliedschaft behalten werden [...] wieder in 2026
# Mitglieder sein") — voir apps.membres.models.HistoriqueStatutMembre pour le détail.
#
# La RunPython reconstruit une première version RÉTROACTIVE de cet historique à partir des
# `Cotisation` (type_article=cotisation) déjà existantes : chaque année entre l'adhésion d'un
# membre et l'année en cours reçoit une entrée "actif" (si une cotisation payée existe pour
# cette année) ou "inactif" (sinon, pour toute année déjà entièrement passée — jamais pour
# l'année en cours, dont l'échéance n'est pas nécessairement dépassée). Ne touche jamais au
# statut COURANT (Membre.statut) ni ne déclenche de notification/email — voir docstring du
# modèle et de apps.membres.services.enregistrer_statut_annuel, qui seuls le font désormais pour
# tout changement à partir de maintenant. Irréversible proprement (impossible de distinguer,
# après coup, ces lignes reconstruites de lignes déjà organiquement créées par le pipeline live
# depuis) : le reverse est un no-op assumé, comme la migration 0006 de apps.cotisations pour un
# cas similaire.

from datetime import datetime, timezone as dt_timezone

import django.db.models.deletion
from django.db import migrations, models

import uuid


def construire_historique_retroactif(apps, schema_editor):
    Membre = apps.get_model("membres", "Membre")
    Cotisation = apps.get_model("cotisations", "Cotisation")
    HistoriqueStatutMembre = apps.get_model("membres", "HistoriqueStatutMembre")

    annee_courante = datetime.now(dt_timezone.utc).year

    for membre in Membre.objects.all().iterator():
        if not membre.date_adhesion:
            continue
        premiere_annee = membre.date_adhesion.year

        paiements = {
            c.annee: c.date_paiement
            for c in Cotisation.objects.filter(
                membre=membre,
                type_article="cotisation",
                statut="payee",
                annee__isnull=False,
            )
        }

        for annee in range(premiere_annee, annee_courante + 1):
            if annee in paiements:
                HistoriqueStatutMembre.objects.get_or_create(
                    membre=membre,
                    annee=annee,
                    defaults={
                        "statut": "actif",
                        "raison": "paiement_confirme",
                        "date_effet": paiements[annee] or datetime(annee, 1, 1, tzinfo=dt_timezone.utc),
                    },
                )
            elif annee < annee_courante:
                # Année entièrement passée sans cotisation payée retrouvée : reconstruite comme
                # inactive — l'année en cours (annee == annee_courante) n'est volontairement
                # jamais reconstruite ici, le pipeline live (checkpoint J+1) s'en charge le
                # moment venu, exactement comme pour un membre qui n'existait pas encore avant
                # cette migration.
                HistoriqueStatutMembre.objects.get_or_create(
                    membre=membre,
                    annee=annee,
                    defaults={
                        "statut": "inactif",
                        "raison": "echeance_depassee",
                        "date_effet": datetime(annee, 1, 1, tzinfo=dt_timezone.utc),
                    },
                )


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0003_membre_pays_alter_membre_adresse_de_and_more"),
        ("cotisations", "0006_articlecatalogue_type_fixe"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoriqueStatutMembre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("annee", models.PositiveSmallIntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("en_attente", "En attente"),
                            ("inactif", "Inactif"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "raison",
                    models.CharField(
                        choices=[
                            ("paiement_confirme", "Paiement confirmé"),
                            ("echeance_depassee", "Échéance dépassée"),
                            ("manuel", "Modification manuelle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "date_effet",
                    models.DateTimeField(
                        help_text=(
                            "Date/heure de l'événement à l'origine de ce statut (paiement ou "
                            "échéance)."
                        )
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_statuts",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de statut membre",
                "verbose_name_plural": "Historiques de statut membre",
                "db_table": "historique_statuts_membre",
                "ordering": ["-annee"],
            },
        ),
        migrations.AddConstraint(
            model_name="historiquestatutmembre",
            constraint=models.UniqueConstraint(
                fields=("membre", "annee"), name="unique_historique_statut_par_membre_annee"
            ),
        ),
        migrations.RunPython(construire_historique_retroactif, migrations.RunPython.noop),
    ]
