# Generated by Django 4.2.16 on 2026-09-28 20:28

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0004_historique_statut_membre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="cin",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
