# Generated by Django 4.2.16 on 2026-09-29 06:39

import apps.membres.models
import apps.membres.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0005_alter_membre_cin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.membres.storage.MembrePhotoStorage(),
                upload_to=apps.membres.models.membre_photo_upload_path,
            ),
        ),
    ]
