# Generated by Django 4.2.16 on 2026-10-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0006_alter_membre_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historiquestatutmembre",
            name="raison",
            field=models.CharField(
                choices=[
                    ("paiement_confirme", "Paiement confirmé"),
                    ("echeance_depassee", "Échéance dépassée"),
                    ("manuel", "Modification manuelle"),
                    ("non_renouvele", "Adhésion non renouvelée"),
                ],
                max_length=20,
            ),
        ),
    ]
