# Generated by Django 4.2.16 on 2026-09-12 18:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membres", "0003_membre_pays_alter_membre_adresse_de_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="Objet du vote, règles, candidats éligibles — mockup #cv-desc."
                    ),
                ),
                (
                    "type_vote",
                    models.CharField(
                        choices=[
                            ("unique", "Choix unique"),
                            ("multiple", "Choix multiple"),
                            ("oui_non", "Oui / Non"),
                            ("preferentiel", "Vote préférentiel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mode_anonymat",
                    models.CharField(
                        choices=[("anonyme", "Anonyme"), ("nominatif", "Nominatif")],
                        default="anonyme",
                        max_length=20,
                    ),
                ),
                (
                    "nb_choix_max",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Nombre de choix autorisés — pertinent uniquement pour type_vote=multiple.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "eligibilite",
                    models.CharField(
                        choices=[
                            ("tous_actifs", "Tous les membres actifs"),
                            ("cotisants", "Membres cotisants de l'année en cours"),
                            ("bureau", "Bureau et modérateurs (Bureau Admin+)"),
                            ("selection_manuelle", "Sélection manuelle"),
                        ],
                        default="tous_actifs",
                        max_length=30,
                    ),
                ),
                (
                    "duree_minutes",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(10080),
                        ]
                    ),
                ),
                (
                    "quorum_pct",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="% minimum de participation requis — null = pas de quorum.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "resultats_visibles_avant_cloture",
                    models.BooleanField(
                        default=False,
                        help_text="Réservé à un usage futur — SCD §7.5 impose que l'API résultats masque systématiquement les comptages tant que statut != cloturee, quelle que soit la valeur de ce champ (voir VoteSessionViewSet.resultats).",
                    ),
                ),
                ("anonymat_sel", encrypted_model_fields.fields.EncryptedCharField(editable=False)),
                (
                    "statut",
                    models.CharField(
                        choices=[("ouverte", "Ouverte"), ("cloturee", "Clôturée")],
                        default="ouverte",
                        max_length=20,
                    ),
                ),
                ("date_ouverture", models.DateTimeField(auto_now_add=True)),
                (
                    "date_fin",
                    models.DateTimeField(
                        help_text="date_ouverture + duree_minutes — calculé à la création, jamais côté client."
                    ),
                ),
                ("date_cloture", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions_vote_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membres_selectionnes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Utilisé uniquement si eligibilite=selection_manuelle.",
                        related_name="votes_selection_manuelle",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session de vote",
                "verbose_name_plural": "Sessions de vote",
                "db_table": "vote_sessions",
                "ordering": ["-date_ouverture"],
            },
        ),
        migrations.CreateModel(
            name="VoteOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Biographie / programme — optionnel."),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="vote.votesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option de vote",
                "verbose_name_plural": "Options de vote",
                "db_table": "vote_options",
                "ordering": ["ordre", "label"],
            },
        ),
        migrations.CreateModel(
            name="VoteExprime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("voter_token_hash", models.CharField(editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulletins",
                        to="vote.votesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulletin exprimé",
                "verbose_name_plural": "Bulletins exprimés",
                "db_table": "vote_exprimes",
            },
        ),
        migrations.CreateModel(
            name="ParticipationVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations_vote",
                        to="membres.membre",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="vote.votesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation (nominatif)",
                "verbose_name_plural": "Participations (nominatif)",
                "db_table": "vote_participations",
            },
        ),
        migrations.CreateModel(
            name="ChoixExprime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rang", models.PositiveSmallIntegerField(default=0)),
                (
                    "bulletin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choix",
                        to="vote.voteexprime",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choix_recus",
                        to="vote.voteoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Choix exprimé",
                "verbose_name_plural": "Choix exprimés",
                "db_table": "vote_choix_exprimes",
            },
        ),
        migrations.AddIndex(
            model_name="votesession",
            index=models.Index(fields=["statut", "date_fin"], name="vote_sessio_statut_9618eb_idx"),
        ),
        migrations.AddConstraint(
            model_name="voteexprime",
            constraint=models.UniqueConstraint(
                fields=("session", "voter_token_hash"), name="unique_voter_token_par_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="participationvote",
            constraint=models.UniqueConstraint(
                fields=("session", "membre"), name="unique_participation_membre"
            ),
        ),
    ]
