# Generated by Django 4.2.16 on 2026-09-12 20:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_planifier_cloture_votes"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteOptionCandidat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidats",
                        to="vote.voteoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidat de liste",
                "verbose_name_plural": "Candidats de liste",
                "db_table": "vote_option_candidats",
                "ordering": ["ordre", "nom"],
            },
        ),
    ]
