# Generated by Django 4.2.16 on 2026-09-25 07:53, retouché à la main : `makemigrations`
# proposait RemoveField+AddField (perte des valeurs existantes) plutôt qu'un vrai
# RenameField — corrigé ici pour préserver les valeurs déjà en base (Railway production
# comprise), voir docstring de VoteSession.seuil_victoire_pct pour le contexte du
# renommage/changement de sémantique (2026-09-25, retour utilisateur).

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0003_voteoptioncandidat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="votesession",
            old_name="quorum_pct",
            new_name="seuil_victoire_pct",
        ),
        migrations.AlterField(
            model_name="votesession",
            name="seuil_victoire_pct",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text=(
                    "% des voix exprimées que l'option arrivée en tête doit dépasser "
                    "STRICTEMENT pour que le vote soit considéré comme décidé — null = pas "
                    "de seuil (la majorité simple/relative suffit). Champ renommé le "
                    "2026-09-25 (retour utilisateur : l'ancien champ `quorum_pct`, un quorum "
                    "de PARTICIPATION comparé avec >=, ne correspondait pas au besoin réel — "
                    "un seuil sur la PART DES VOIX du gagnant, comparé avec > strict) — voir "
                    "services.calculer_resultats."
                ),
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
