# Generated by Django 4.2.16 on 2026-09-11 23:40

import apps.boutique.models
import apps.boutique.storage
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membres", "0003_membre_pays_alter_membre_adresse_de_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("numero_commande", models.CharField(editable=False, max_length=30, unique=True)),
                ("nom_destinataire", models.CharField(max_length=200)),
                ("adresse_livraison", models.CharField(max_length=255)),
                ("code_postal_livraison", models.CharField(max_length=10)),
                ("ville_livraison", models.CharField(max_length=100)),
                ("pays_livraison", models.CharField(default="Allemagne", max_length=100)),
                ("telephone_livraison", models.CharField(blank=True, max_length=30)),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Recalculé côté serveur = somme des lignes (CLAUDE.md §8).",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("confirmee", "Confirmée"),
                            ("en_preparation", "En préparation"),
                            ("expediee", "Expédiée"),
                            ("livree", "Livrée"),
                            ("annulee", "Annulée"),
                            ("remboursee", "Remboursée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "db_table": "boutique_commandes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de commande",
                "verbose_name_plural": "Lignes de commande",
                "db_table": "boutique_lignes_commande",
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("vetements", "Vêtements"),
                            ("accessoires", "Accessoires"),
                            ("articles_club", "Articles club"),
                            ("cartes_docs", "Cartes & Docs"),
                            ("divers", "Divers"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=apps.boutique.storage.ProduitsStorage(),
                        upload_to=apps.boutique.models.produit_image_upload_path,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("publie", "Publié"),
                            ("archive", "Archivé"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                (
                    "nouveaute",
                    models.BooleanField(
                        default=False, help_text='Affiche le badge "Nouveauté" dans le catalogue.'
                    ),
                ),
                (
                    "seuil_alerte_stock",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Alerte admin quand le stock total d'une variante passe en dessous.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
                "db_table": "boutique_produits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VarianteProduit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("taille", models.CharField(blank=True, max_length=20)),
                ("couleur", models.CharField(blank=True, max_length=50)),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variantes",
                        to="boutique.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante produit",
                "verbose_name_plural": "Variantes produit",
                "db_table": "boutique_variantes",
                "ordering": ["produit", "taille", "couleur"],
            },
        ),
        migrations.AddIndex(
            model_name="produit",
            index=models.Index(
                fields=["statut", "categorie"], name="boutique_pr_statut_2fcf72_idx"
            ),
        ),
        migrations.AddField(
            model_name="lignecommande",
            name="commande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="boutique.commande",
            ),
        ),
        migrations.AddField(
            model_name="lignecommande",
            name="variante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_commande",
                to="boutique.varianteproduit",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="membre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commandes",
                to="membres.membre",
            ),
        ),
        migrations.AddConstraint(
            model_name="varianteproduit",
            constraint=models.UniqueConstraint(
                fields=("produit", "taille", "couleur"), name="une_seule_variante_par_combinaison"
            ),
        ),
        migrations.AddIndex(
            model_name="commande",
            index=models.Index(fields=["membre", "statut"], name="boutique_co_membre__a9d648_idx"),
        ),
        migrations.AddIndex(
            model_name="commande",
            index=models.Index(fields=["statut"], name="boutique_co_statut_b718b5_idx"),
        ),
    ]
