# Generated by Django 4.2.16 on 2026-09-12 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="pourcentage_reduction",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Rabais optionnel (1 à 90 %) appliqué au prix catalogue — voir prix_final.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
    ]
