# Generated by Django 4.2.16 on 2026-09-15 21:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0003_membre_pays_alter_membre_adresse_de_and_more"),
        ("boutique", "0002_produit_pourcentage_reduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="date_expedition",
            field=models.DateTimeField(
                blank=True,
                help_text="Date réelle d'expédition — normalement la date de l'action, mais éditable pour une saisie rétroactive (nacherfassement).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="date_paiement_confirme",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commande",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en_ligne", "Paiement en ligne"),
                    ("virement", "Virement SEPA"),
                    ("especes", "Espèces"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="numero_suivi",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="commande",
            name="paiement_confirme_par",
            field=models.ForeignKey(
                blank=True,
                help_text="Directeur Financier/Admin ayant confirmé la réception du paiement.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commandes_paiement_confirme",
                to="membres.membre",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="transporteur",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="Retour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("defectueux", "Article défectueux/abîmé"),
                            ("mauvaise_taille", "Mauvaise taille"),
                            ("ne_convient_pas", "Ne convient pas"),
                            ("erreur_envoi", "Erreur d'envoi"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retours",
                        to="boutique.commande",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retours_enregistres",
                        to="membres.membre",
                    ),
                ),
                (
                    "ligne_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retours",
                        to="boutique.lignecommande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retoure",
                "verbose_name_plural": "Retoures",
                "db_table": "boutique_retours",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["commande"], name="boutique_re_command_04b17b_idx")
                ],
            },
        ),
    ]
