# Generated by Django 4.2.16 on 2026-09-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0003_membre_pays_alter_membre_adresse_de_and_more"),
        ("boutique", "0003_commande_date_expedition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="reference_paiement",
            field=models.CharField(
                blank=True,
                help_text="Référence externe du paiement (PSP), ex. STRIPE-pi_xxx / PAYPAL-xxx — renseignée uniquement pour un paiement confirmé automatiquement via webhook (voir apps.boutique.webhooks), jamais pour une confirmation manuelle.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="paiement_confirme_par",
            field=models.ForeignKey(
                blank=True,
                help_text="Directeur Financier/Admin ayant confirmé la réception du paiement — vide pour une confirmation automatique par webhook PSP (voir reference_paiement).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commandes_paiement_confirme",
                to="membres.membre",
            ),
        ),
    ]
