# Generated by Django 4.2.16 on 2026-09-23 08:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0004_historique_statut_membre"),
        ("boutique", "0004_commande_reference_paiement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonAchat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=20, unique=True)),
                (
                    "montant_initial",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("5.00")),
                            django.core.validators.MaxValueValidator(Decimal("500.00")),
                        ],
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de paiement"),
                            ("actif", "Actif"),
                            ("epuise", "Épuisé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en_ligne", "Paiement en ligne"),
                            ("virement", "Virement SEPA"),
                            ("especes", "Espèces"),
                            ("bon_achat", "Bon d'achat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_paiement_confirme", models.DateTimeField(blank=True, null=True)),
                ("reference_paiement", models.CharField(blank=True, max_length=64)),
                (
                    "date_expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Renseignée à l'activation (statut=ACTIF) = date_paiement_confirme + DUREE_VALIDITE_BON_ACHAT.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "achete_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bons_achat_achetes",
                        to="membres.membre",
                    ),
                ),
                (
                    "paiement_confirme_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Directeur Financier/Admin ayant confirmé un paiement manuel — vide pour un paiement en ligne confirmé automatiquement par webhook PSP.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bons_achat_paiement_confirme",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon d'achat",
                "verbose_name_plural": "Bons d'achat",
                "db_table": "boutique_bons_achat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="commande",
            name="montant_bon_achat",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Montant déduit via bon_achat — voir UtilisationBonAchat pour le journal.",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="lignecommande",
            name="pourcentage_reduction_quantite",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lignecommande",
            name="quantite_offerte",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lignecommande",
            name="reduction_quantite",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en_ligne", "Paiement en ligne"),
                    ("virement", "Virement SEPA"),
                    ("especes", "Espèces"),
                    ("bon_achat", "Bon d'achat"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RegleReduction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "seuil_quantite",
                    models.PositiveIntegerField(
                        help_text="Quantité du même produit à atteindre dans la commande pour déclencher la règle.",
                        validators=[django.core.validators.MinValueValidator(2)],
                    ),
                ),
                (
                    "type_reduction",
                    models.CharField(
                        choices=[
                            ("pourcentage", "Pourcentage de réduction"),
                            ("article_offert", "Article(s) offert(s)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pourcentage",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Requis et unique sens pour type_reduction=pourcentage — voir clean().",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regles_reduction",
                        to="boutique.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle de réduction",
                "verbose_name_plural": "Règles de réduction",
                "db_table": "boutique_regles_reduction",
                "ordering": ["produit", "seuil_quantite"],
            },
        ),
        migrations.AddField(
            model_name="commande",
            name="bon_achat",
            field=models.ForeignKey(
                blank=True,
                help_text="Bon d'achat appliqué à cette commande, le cas échéant — voir montant_du.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commandes",
                to="boutique.bonachat",
            ),
        ),
        migrations.CreateModel(
            name="UtilisationBonAchat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bon_achat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utilisations",
                        to="boutique.bonachat",
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utilisations_bon_achat",
                        to="boutique.commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisation de bon d'achat",
                "verbose_name_plural": "Utilisations de bon d'achat",
                "db_table": "boutique_utilisations_bon_achat",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["bon_achat"], name="boutique_ut_bon_ach_3b48ec_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="reglereduction",
            constraint=models.UniqueConstraint(
                fields=("produit", "seuil_quantite"), name="un_seul_palier_par_seuil_et_produit"
            ),
        ),
        migrations.AddIndex(
            model_name="bonachat",
            index=models.Index(fields=["code"], name="boutique_bo_code_ffc611_idx"),
        ),
        migrations.AddIndex(
            model_name="bonachat",
            index=models.Index(
                fields=["achete_par", "statut"], name="boutique_bo_achete__aec40e_idx"
            ),
        ),
    ]
