# Generated by Django 4.2.16 on 2026-09-23 10:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0005_bonachat_commande_montant_bon_achat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="type_produit",
            field=models.CharField(
                choices=[("physique", "Produit physique"), ("bon_achat", "Bon d'achat")],
                default="physique",
                help_text="Physique (stock réel) ou bon d'achat (montant choisi par l'acheteur, sans stock) — voir docstring de tête du module.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bonachat",
            name="statut",
            field=models.CharField(
                choices=[("actif", "Actif"), ("epuise", "Épuisé")],
                default="actif",
                help_text="Toujours ACTIF dès la création depuis le 2026-09-23 — voir views._generer_bons_achat/activer().",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("vetements", "Vêtements"),
                    ("accessoires", "Accessoires"),
                    ("articles_club", "Articles club"),
                    ("cartes_docs", "Cartes & Docs"),
                    ("divers", "Divers"),
                    ("bon_achat", "Bons d'achat"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="prix",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Pour un bon d'achat (type_produit=BON_ACHAT), ce prix catalogue n'est qu'indicatif (« à partir de ») — le montant réellement facturé est choisi par l'acheteur au moment de l'ajout au panier, borné à [bon_achat_montant_min, bon_achat_montant_max] et toujours revalidé côté serveur, jamais ce champ.",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
