# Generated by Django 4.2.16 on 2026-09-26 11:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0006_produit_type_produit_alter_bonachat_statut_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="prix_membre",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prix optionnel réservé aux membres actifs (demande utilisateur, mycid.org/shop — badge « Mitglieder Preis »). Quand il est défini, un membre CONNECTÉ et ACTIF (StatutMembre.ACTIF) voit et paie CE prix au lieu de prix_final ; tout autre acheteur (non connecté, non-membre, membre en_attente/inactif) continue de payer prix_final, sans lien avec ce champ. Ne se cumule jamais avec pourcentage_reduction — voir prix_pour_membre(), seul point qui résout laquelle des deux remises s'applique, toujours recalculé côté serveur (CLAUDE.md §8, même choke point que prix_final : CommandeViewSet._construire_ligne_avec_reduction).",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
