# Generated by Django 4.2.16 on 2026-09-27 09:41

import apps.boutique.models
import apps.boutique.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0004_historique_statut_membre"),
        ("boutique", "0007_produit_prix_membre"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProduitImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=apps.boutique.storage.ProduitsStorage(),
                        upload_to=apps.boutique.models.produit_image_galerie_upload_path,
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="boutique.produit",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image de produit",
                "verbose_name_plural": "Images de produit",
                "db_table": "boutique_produits_images",
                "ordering": ["ordre", "created_at"],
            },
        ),
    ]
