# Generated by Django 4.2.16 on 2026-09-23 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_system", models.BooleanField(default=False)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rôle",
                "verbose_name_plural": "Rôles",
                "db_table": "rbac_role_definitions",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="UserRoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_assignments",
                        to="rbac.roledefinition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribution de rôle",
                "verbose_name_plural": "Attributions de rôle",
                "db_table": "rbac_user_role_assignments",
            },
        ),
        migrations.CreateModel(
            name="RoleModulePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("module", models.CharField(max_length=50)),
                (
                    "niveau_acces",
                    models.CharField(
                        choices=[
                            ("aucun", "Aucun accès"),
                            ("lecture", "Lecture seule"),
                            ("lecture_ecriture", "Lecture et écriture"),
                        ],
                        default="aucun",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_permissions",
                        to="rbac.roledefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission de module",
                "verbose_name_plural": "Permissions de module",
                "db_table": "rbac_role_module_permissions",
            },
        ),
        migrations.CreateModel(
            name="ModuleVisibiliteMembre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("module", models.CharField(max_length=50, unique=True)),
                ("visible", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Visibilité de module (Membre Normal)",
                "verbose_name_plural": "Visibilité de modules (Membre Normal)",
                "db_table": "rbac_module_visibilite_membre",
            },
        ),
        migrations.AddConstraint(
            model_name="userroleassignment",
            constraint=models.UniqueConstraint(
                fields=("user", "role"), name="une_seule_ligne_par_user_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="rolemodulepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "module"), name="une_seule_cellule_par_role_module"
            ),
        ),
    ]
