# Generated by Django 4.2.16 on 2026-10-05 17:39

from django.db import migrations, models

# Copie figée (une migration ne doit jamais importer un registre applicatif qui évoluera).
CLES = [
    "membres", "cotisations", "adhesions", "evenements", "boutique", "vote",
    "communaute", "stats", "notifications", "projets", "albums",
]
DEFAUT_NON_MEMBRE = {"adhesions", "evenements", "projets", "boutique", "albums"}


def initialiser(apps, schema_editor):
    """Une ligne par clé (visible pour les membres = inchangé), colonne non-membre initialisée
    au défaut demandé (2026-10-05, point 3) — rend la liste complète et éditable dans l'admin
    Django dès le déploiement."""
    Ligne = apps.get_model("rbac", "ModuleVisibiliteMembre")
    for cle in CLES:
        ligne, _ = Ligne.objects.get_or_create(module=cle, defaults={"visible": True})
        if ligne.visible_non_membre is None:
            ligne.visible_non_membre = cle in DEFAUT_NON_MEMBRE
            ligne.save(update_fields=["visible_non_membre"])


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0003_seed_pages_admin_matrice"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulevisibilitemembre",
            name="visible_non_membre",
            field=models.BooleanField(
                blank=True,
                help_text="Vide = valeur par défaut (visible pour 5 modules, voir registry).",
                null=True,
                verbose_name="Visible pour non-membre",
            ),
        ),
        migrations.RunPython(initialiser, migrations.RunPython.noop),
    ]
