# Generated by Django 4.2.16 on 2026-09-10 12:40

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("membre", "Membre Normal"),
                            ("rh", "Ressources Humaines"),
                            ("bureau_admin", "Membre Bureau Administratif"),
                            ("dir_financier", "Directeur Financier"),
                            ("super_admin", "Administrateur App"),
                        ],
                        default="membre",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Un membre inscrit doit être activé par RH ou Admin (FDD §3.1).",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "langue_preferee",
                    models.CharField(
                        choices=[("fr", "Français"), ("de", "Deutsch"), ("ar", "العربية")],
                        default="fr",
                        max_length=2,
                    ),
                ),
                (
                    "require_2fa",
                    models.BooleanField(
                        default=False, help_text="Force le 2FA même pour un Membre Normal."
                    ),
                ),
                ("last_known_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("trusted_device_token", models.CharField(blank=True, max_length=64, null=True)),
                ("last_successful_login", models.DateTimeField(blank=True, null=True)),
                (
                    "notes_securite",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": "users",
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login_2fa", "Connexion 2FA"),
                            ("password_reset", "Réinitialisation MDP"),
                        ],
                        default="login_2fa",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_otps",
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "consumed_at"],
                        name="email_otps_user_id_a95300_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log_entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"], name="audit_log_e_action_340c82_idx"
                    )
                ],
            },
        ),
    ]
