# Generated by Django 4.2.16 on 2026-09-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_decision",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("approuve", "Approuvée"),
                    ("refuse", "Refusée"),
                ],
                default="en_attente",
                help_text="Décision RH/Admin sur cette inscription — distinct de is_active qui peut aussi être False pour d'autres raisons.",
                max_length=20,
            ),
        ),
    ]
