# Generated by Django 4.2.16 on 2026-09-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_registration_decision"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verifie",
            field=models.BooleanField(
                default=False,
                help_text="Code à 6 chiffres confirmé après inscription. Un superuser ou un compte créé par import (create_user hors self-registration) n'a pas besoin de ce garde-fou — voir UserManager.",
            ),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("login_2fa", "Connexion 2FA"),
                    ("password_reset", "Réinitialisation MDP"),
                    ("email_verification", "Vérification email inscription"),
                ],
                default="login_2fa",
                max_length=20,
            ),
        ),
    ]
