# Generated by Django 4.2.16 on 2026-09-24 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("token_blacklist", "0012_alter_outstandingtoken_user"),
        ("accounts", "0003_user_email_verifie_alter_emailotp_purpose"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("device_fingerprint_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outstanding_token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_session",
                        to="token_blacklist.outstandingtoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "device_sessions",
                "indexes": [
                    models.Index(
                        fields=["user", "device_fingerprint_hash"],
                        name="device_sess_user_id_e7142b_idx",
                    )
                ],
            },
        ),
    ]
