# Generated by Django 4.2.16 on 2026-10-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_planifier_nettoyage_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
