# Generated by Django 4.2.16 on 2026-09-10 21:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membres", "0002_alter_membre_date_adhesion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotisation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type_article",
                    models.CharField(
                        choices=[
                            ("cotisation", "Cotisation annuelle"),
                            ("adhesion", "Frais d'adhésion"),
                            ("evenement", "Événement"),
                            ("don", "Don libre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("libelle", models.CharField(max_length=200)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("carte", "Carte bancaire"),
                            ("virement_sepa", "Virement SEPA"),
                            ("paypal", "PayPal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("payee", "Payée"),
                            ("echouee", "Échouée"),
                            ("remboursee", "Remboursée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "reference_transaction",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("annee", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("date_paiement", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotisations",
                        to="membres.membre",
                    ),
                ),
                (
                    "saisie_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Renseigné uniquement si la transaction a été ajoutée manuellement par le Directeur Financier/Admin pour le compte d'un autre membre (F-015). Vide en libre-service.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotisations_saisies",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotisation",
                "verbose_name_plural": "Cotisations",
                "db_table": "cotisations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["membre", "type_article", "annee"],
                        name="cotisations_membre__15430a_idx",
                    ),
                    models.Index(fields=["statut"], name="cotisations_statut_fe7052_idx"),
                ],
            },
        ),
    ]
