# Generated by Django 4.2.16 on 2026-09-11 21:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0003_membre_pays_alter_membre_adresse_de_and_more"),
        ("cotisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelanceCotisation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("annee", models.PositiveSmallIntegerField()),
                (
                    "checkpoint",
                    models.CharField(
                        choices=[("j_moins_30", "J-30"), ("j_moins_7", "J-7"), ("j_plus_1", "J+1")],
                        max_length=20,
                    ),
                ),
                ("envoyee_le", models.DateTimeField(auto_now_add=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relances_cotisation",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relance cotisation",
                "verbose_name_plural": "Relances cotisation",
                "db_table": "relances_cotisation",
                "ordering": ["-envoyee_le"],
            },
        ),
        migrations.AddConstraint(
            model_name="relancecotisation",
            constraint=models.UniqueConstraint(
                fields=("membre", "annee", "checkpoint"),
                name="unique_relance_par_membre_annee_checkpoint",
            ),
        ),
    ]
