# Generated by Django 4.2.16 on 2026-09-11 21:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0003_membre_pays_alter_membre_adresse_de_and_more"),
        ("cotisations", "0003_planifier_relance_cotisation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationRelance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "annee",
                    models.PositiveSmallIntegerField(
                        help_text="Année de cotisation à laquelle s'applique cette échéance.",
                        unique=True,
                    ),
                ),
                (
                    "date_echeance",
                    models.DateField(
                        help_text="Date à partir de laquelle la cotisation de cette année est en retard."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Directeur Financier/Admin ayant défini ou modifié cette échéance en dernier.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration de relance",
                "verbose_name_plural": "Configurations de relance",
                "db_table": "configurations_relance",
                "ordering": ["-annee"],
            },
        ),
    ]
