# Generated by Django 4.2.16 on 2026-09-16 22:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cotisations", "0004_configurationrelance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCatalogue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("libelle", models.CharField(max_length=200)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Article du catalogue",
                "verbose_name_plural": "Articles du catalogue",
                "db_table": "cotisations_articles_catalogue",
                "ordering": ["libelle"],
            },
        ),
        migrations.AlterField(
            model_name="cotisation",
            name="type_article",
            field=models.CharField(
                choices=[
                    ("cotisation", "Cotisation annuelle"),
                    ("adhesion", "Frais d'adhésion"),
                    ("evenement", "Événement"),
                    ("don", "Don libre"),
                    ("autre", "Article personnalisé"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cotisation",
            name="article_catalogue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cotisations",
                to="cotisations.articlecatalogue",
            ),
        ),
    ]
