# Generated by Django 4.2.16 on 2026-09-16 23:32
#
# Complétée manuellement le 2026-09-17 (retour utilisateur : "die bestehende [Cotisation
# annuelle/Frais d'adhésion] müssen auch verwaltbar sein") : seed des 2 lignes techniques
# ArticleCatalogue.type_fixe représentant les tarifs cotisation/adhésion, avec les montants
# historiquement figés dans MONTANTS_CATALOGUE (45.00 €/15.00 €) — voir apps.cotisations.models.
# get_or_create (jamais get_or_none) : idempotent si la migration est rejouée, et ne duplique
# jamais ces 2 lignes si elles existent déjà (ex. ré-application après un rollback partiel).

from decimal import Decimal

from django.db import migrations, models


def seed_articles_fixes(apps, schema_editor):
    ArticleCatalogue = apps.get_model("cotisations", "ArticleCatalogue")
    ArticleCatalogue.objects.get_or_create(
        type_fixe="cotisation",
        defaults={"libelle": "Cotisation annuelle", "montant": Decimal("45.00"), "actif": True},
    )
    ArticleCatalogue.objects.get_or_create(
        type_fixe="adhesion",
        defaults={"libelle": "Frais d'adhésion", "montant": Decimal("15.00"), "actif": True},
    )


def retirer_articles_fixes(apps, schema_editor):
    # Reverse : supprime les 2 lignes de seed (jamais de Cotisation historique ne les référence
    # via une FK — voir Cotisation.article_catalogue, réservé au type "autre" — donc pas de
    # on_delete=PROTECT à contourner ici).
    ArticleCatalogue = apps.get_model("cotisations", "ArticleCatalogue")
    ArticleCatalogue.objects.filter(type_fixe__in=["cotisation", "adhesion"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("cotisations", "0005_articlecatalogue_alter_cotisation_type_article_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlecatalogue",
            name="type_fixe",
            field=models.CharField(
                blank=True,
                choices=[("cotisation", "Cotisation annuelle"), ("adhesion", "Frais d'adhésion")],
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(seed_articles_fixes, retirer_articles_fixes),
    ]
