# Generated by Django 4.2.16 on 2026-09-19 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0004_historique_statut_membre"),
        ("cotisations", "0006_articlecatalogue_type_fixe"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoriqueStatutCotisation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ancien_statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("payee", "Payée"),
                            ("echouee", "Échouée"),
                            ("remboursee", "Remboursée"),
                            ("annulee", "Annulée"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nouveau_statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("payee", "Payée"),
                            ("echouee", "Échouée"),
                            ("remboursee", "Remboursée"),
                            ("annulee", "Annulée"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "motif",
                    models.TextField(
                        blank=True,
                        help_text="Raison de la correction, saisie par le Directeur Financier/Admin — vide pour une transition automatique (ex. marquer_payee sans motif renseigné).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cotisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_statuts",
                        to="cotisations.cotisation",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Directeur Financier/Admin à l'origine de ce changement de statut.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de statut de cotisation",
                "verbose_name_plural": "Historiques de statut de cotisation",
                "db_table": "cotisations_historique_statuts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["cotisation"], name="cotisations_cotisat_fe7456_idx")
                ],
            },
        ),
    ]
