# Generated by Django 4.2.16 on 2026-09-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotisations", "0007_historiquestatutcotisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotisation",
            name="mode_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("carte", "Carte bancaire"),
                    ("virement_sepa", "Virement SEPA"),
                    ("paypal", "PayPal"),
                    ("especes", "Espèces"),
                ],
                max_length=20,
            ),
        ),
    ]
