# Generated by Django 4.2.16 on 2026-09-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotisations", "0008_ajoute_mode_paiement_especes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotisation",
            name="type_article",
            field=models.CharField(
                choices=[
                    ("cotisation", "Cotisation annuelle"),
                    ("adhesion", "Frais d'adhésion"),
                    ("evenement", "Événement"),
                    ("don", "Don libre"),
                    ("autre", "Article personnalisé"),
                    ("autre_libre", "Autre (libre)"),
                ],
                max_length=20,
            ),
        ),
    ]
