# Generated by Django 4.2.16 on 2026-09-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projets", "0001_initial"),
        ("cotisations", "0009_ajoute_type_article_autre_libre"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotisation",
            name="projet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contributions",
                to="projets.projet",
            ),
        ),
        migrations.AlterField(
            model_name="cotisation",
            name="type_article",
            field=models.CharField(
                choices=[
                    ("cotisation", "Cotisation annuelle"),
                    ("adhesion", "Frais d'adhésion"),
                    ("evenement", "Événement"),
                    ("don", "Don libre"),
                    ("autre", "Article personnalisé"),
                    ("autre_libre", "Autre (libre)"),
                    ("projet", "Contribution à un projet"),
                ],
                max_length=20,
            ),
        ),
    ]
