# Generated by Django 4.2.16 on 2026-09-13 04:49

import apps.communaute.models
import apps.communaute.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membres", "0003_membre_pays_alter_membre_adresse_de_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Hashtag",
                "verbose_name_plural": "Hashtags",
                "db_table": "communaute_hashtags",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contenu", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=apps.communaute.storage.PublicationsStorage(),
                        upload_to=apps.communaute.models.publication_image_upload_path,
                    ),
                ),
                (
                    "est_masquee",
                    models.BooleanField(
                        default=False,
                        help_text="Modération admin — soft-hide, préserve l'historique.",
                    ),
                ),
                ("motif_masquage", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="membres.membre",
                    ),
                ),
                (
                    "hashtags",
                    models.ManyToManyField(
                        blank=True, related_name="publications", to="communaute.hashtag"
                    ),
                ),
                (
                    "masquee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications_masquees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "db_table": "communaute_publications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sujet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("football_ca", "Football CA"),
                            ("vie_en_allemagne", "Vie en Allemagne"),
                            ("emploi", "Emploi & Business"),
                            ("general", "Général"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.TextField()),
                (
                    "est_epingle",
                    models.BooleanField(default=False, help_text="Remonte en tête de liste."),
                ),
                (
                    "est_verrouille",
                    models.BooleanField(
                        default=False,
                        help_text="Bloque les nouvelles réponses sans masquer le sujet.",
                    ),
                ),
                (
                    "est_masque",
                    models.BooleanField(default=False, help_text="Modération admin — soft-hide."),
                ),
                ("motif_masquage", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sujets_forum",
                        to="membres.membre",
                    ),
                ),
                (
                    "masque_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sujets_masques",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sujet de forum",
                "verbose_name_plural": "Sujets de forum",
                "db_table": "communaute_forum_sujets",
                "ordering": ["-est_epingle", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReponseForum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contenu", models.TextField()),
                ("est_masquee", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses_forum",
                        to="membres.membre",
                    ),
                ),
                (
                    "sujet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="communaute.sujet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse de forum",
                "verbose_name_plural": "Réponses de forum",
                "db_table": "communaute_forum_reponses",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicationPartage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partages_fil",
                        to="membres.membre",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partages",
                        to="communaute.publication",
                    ),
                ),
            ],
            options={
                "db_table": "communaute_publication_partages",
            },
        ),
        migrations.CreateModel(
            name="PublicationLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_fil",
                        to="membres.membre",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="communaute.publication",
                    ),
                ),
            ],
            options={
                "db_table": "communaute_publication_likes",
            },
        ),
        migrations.CreateModel(
            name="Commentaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contenu", models.TextField()),
                ("est_masque", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires_fil",
                        to="membres.membre",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="communaute.commentaire",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires",
                        to="communaute.publication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
                "db_table": "communaute_commentaires",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sujet",
            index=models.Index(
                fields=["categorie", "est_masque"], name="communaute__categor_5bfbbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reponseforum",
            index=models.Index(
                fields=["sujet", "created_at"], name="communaute__sujet_i_851084_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationpartage",
            constraint=models.UniqueConstraint(
                fields=("publication", "membre"), name="un_seul_partage_par_membre"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationlike",
            constraint=models.UniqueConstraint(
                fields=("publication", "membre"), name="un_seul_like_par_membre"
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["est_masquee", "-created_at"], name="communaute__est_mas_a938ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentaire",
            index=models.Index(
                fields=["publication", "created_at"], name="communaute__publica_ae3703_idx"
            ),
        ),
    ]
