# Generated by Django 4.2.16 on 2026-09-13 05:16

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0003_membre_pays_alter_membre_adresse_de_and_more"),
        ("communaute", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membre_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_a",
                        to="membres.membre",
                    ),
                ),
                (
                    "membre_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_b",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "db_table": "communaute_conversations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupeChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "type_groupe",
                    models.CharField(
                        choices=[("public", "Public"), ("prive", "Privé")],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groupes_crees",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Groupe de chat",
                "verbose_name_plural": "Groupes de chat",
                "db_table": "communaute_groupes_chat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MembreGroupe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membres_groupe",
                        to="communaute.groupechat",
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groupes_rejoints",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre de groupe",
                "verbose_name_plural": "Membres de groupe",
                "db_table": "communaute_membres_groupe",
            },
        ),
        migrations.CreateModel(
            name="MessagePrive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contenu", encrypted_model_fields.fields.EncryptedTextField()),
                ("est_lu", models.BooleanField(default=False)),
                ("lu_le", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communaute.conversation",
                    ),
                ),
                (
                    "expediteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_prives_envoyes",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message privé",
                "verbose_name_plural": "Messages privés",
                "db_table": "communaute_messages_prives",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at"], name="communaute__convers_e51d68_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageGroupe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contenu", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_groupe",
                        to="membres.membre",
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communaute.groupechat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de groupe",
                "verbose_name_plural": "Messages de groupe",
                "db_table": "communaute_messages_groupe",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["groupe", "created_at"], name="communaute__groupe__6207bc_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="membregroupe",
            constraint=models.UniqueConstraint(
                fields=("groupe", "membre"), name="membre_groupe_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("membre_a", "membre_b"), name="conversation_paire_unique"
            ),
        ),
    ]
