# Generated by Django 4.2.16 on 2026-09-14 16:43

import apps.communaute.models
import apps.communaute.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0003_membre_pays_alter_membre_adresse_de_and_more"),
        ("evenements", "0002_planifier_rappels_evenements"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communaute", "0002_conversation_groupechat_membregroupe_messageprive_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums_crees",
                        to="membres.membre",
                    ),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optionnel — un album peut ne pas être rattaché à un événement précis.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="albums",
                        to="evenements.evenement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Album",
                "verbose_name_plural": "Albums",
                "db_table": "communaute_albums",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChoixQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("texte", models.CharField(max_length=255)),
                ("est_correct", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Choix de question",
                "verbose_name_plural": "Choix de question",
                "db_table": "communaute_quiz_choix",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("adversaire", models.CharField(max_length=200)),
                ("competition", models.CharField(blank=True, max_length=200)),
                ("lieu", models.CharField(blank=True, max_length=200)),
                ("date_heure", models.DateTimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_venir", "À venir"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                        ],
                        default="a_venir",
                        max_length=10,
                    ),
                ),
                ("score_ca", models.PositiveSmallIntegerField(default=0)),
                ("score_adversaire", models.PositiveSmallIntegerField(default=0)),
                (
                    "minute_chrono",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Minute affichée pendant que statut=en_cours."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matchs_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matchs",
                "db_table": "communaute_matchs",
                "ordering": ["-date_heure"],
            },
        ),
        migrations.CreateModel(
            name="ParticipationQuiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("demarree_le", models.DateTimeField(auto_now_add=True)),
                ("terminee_le", models.DateTimeField(blank=True, null=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations_quiz",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation quiz",
                "verbose_name_plural": "Participations quiz",
                "db_table": "communaute_quiz_participations",
                "ordering": ["-score", "terminee_le"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=apps.communaute.storage.AlbumsStorage(),
                        upload_to=apps.communaute.models.photo_album_upload_path,
                    ),
                ),
                ("legende", models.CharField(blank=True, max_length=255)),
                (
                    "est_masquee",
                    models.BooleanField(
                        default=False,
                        help_text="Modération admin — soft-hide, préserve l'historique.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="communaute.album",
                    ),
                ),
                (
                    "masquee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos_masquees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos_album",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
                "db_table": "communaute_photos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionQuiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("texte", models.CharField(max_length=500)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "points",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Points attribués si la bonne réponse est sélectionnée.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question de quiz",
                "verbose_name_plural": "Questions de quiz",
                "db_table": "communaute_quiz_questions",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="ReponseQuiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("est_correct", models.BooleanField()),
                ("points_obtenus", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "choix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="communaute.choixquestion",
                    ),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="communaute.participationquiz",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="communaute.questionquiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse de quiz",
                "verbose_name_plural": "Réponses de quiz",
                "db_table": "communaute_quiz_reponses",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "est_actif",
                    models.BooleanField(
                        default=False,
                        help_text="Un seul quiz actif proposé aux membres à la fois (convention d'usage côté admin, pas de contrainte DB — voir docstring de tête).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quiz_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quiz",
                "db_table": "communaute_quiz",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="questionquiz",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="communaute.quiz",
            ),
        ),
        migrations.CreateModel(
            name="PhotoLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_photo",
                        to="membres.membre",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="communaute.photo",
                    ),
                ),
            ],
            options={
                "db_table": "communaute_photo_likes",
            },
        ),
        migrations.CreateModel(
            name="PhotoCommentaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contenu", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires_photo",
                        to="membres.membre",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires",
                        to="communaute.photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire de photo",
                "verbose_name_plural": "Commentaires de photo",
                "db_table": "communaute_photo_commentaires",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="participationquiz",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to="communaute.quiz",
            ),
        ),
        migrations.CreateModel(
            name="MatchReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        choices=[
                            ("coeur", "❤️"),
                            ("feu", "🔥"),
                            ("etoile", "⭐"),
                            ("surprise", "😅"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="communaute.match",
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions_live",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réaction live",
                "verbose_name_plural": "Réactions live",
                "db_table": "communaute_match_reactions",
            },
        ),
        migrations.CreateModel(
            name="MatchCommentaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contenu", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires_live",
                        to="membres.membre",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires",
                        to="communaute.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire live",
                "verbose_name_plural": "Commentaires live",
                "db_table": "communaute_match_commentaires",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="choixquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choix",
                to="communaute.questionquiz",
            ),
        ),
        migrations.AddConstraint(
            model_name="reponsequiz",
            constraint=models.UniqueConstraint(
                fields=("participation", "question"), name="une_reponse_par_question"
            ),
        ),
        migrations.AddIndex(
            model_name="questionquiz",
            index=models.Index(fields=["quiz", "ordre"], name="communaute__quiz_id_fd371b_idx"),
        ),
        migrations.AddConstraint(
            model_name="photolike",
            constraint=models.UniqueConstraint(
                fields=("photo", "membre"), name="un_seul_like_par_membre_photo"
            ),
        ),
        migrations.AddIndex(
            model_name="photocommentaire",
            index=models.Index(
                fields=["photo", "created_at"], name="communaute__photo_i_7eb5a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                fields=["album", "est_masquee", "-created_at"],
                name="communaute__album_i_40dd20_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="participationquiz",
            constraint=models.UniqueConstraint(
                fields=("quiz", "membre"), name="une_participation_par_membre"
            ),
        ),
        migrations.AddIndex(
            model_name="matchreaction",
            index=models.Index(fields=["match", "emoji"], name="communaute__match_i_300fce_idx"),
        ),
        migrations.AddIndex(
            model_name="matchcommentaire",
            index=models.Index(
                fields=["match", "created_at"], name="communaute__match_i_2dd941_idx"
            ),
        ),
    ]
