# Generated by Django 4.2.16 on 2026-09-19 22:38

from django.db import migrations, models

import apps.communaute.models
import apps.communaute.storage


class Migration(migrations.Migration):

    dependencies = [
        ("communaute", "0003_album_choixquestion_match_participationquiz_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="document",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.communaute.storage.PublicationsStorage(),
                upload_to=apps.communaute.models.publication_document_upload_path,
            ),
        ),
    ]
