# Generated by Django 4.2.16 on 2026-09-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communaute", "0004_publication_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Date"),
        ),
        migrations.AddField(
            model_name="album",
            name="lieu",
            field=models.CharField(blank=True, max_length=255, verbose_name="Lieu"),
        ),
    ]
