# Generated by Django 4.2.16 on 2026-09-24 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communaute", "0005_album_date_lieu"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassementLigue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("saison", models.CharField(help_text='Ex. "2025-2026".', max_length=20)),
                ("equipe", models.CharField(max_length=200)),
                ("rang", models.PositiveSmallIntegerField()),
                ("joues", models.PositiveSmallIntegerField(default=0)),
                ("victoires", models.PositiveSmallIntegerField(default=0)),
                ("nuls", models.PositiveSmallIntegerField(default=0)),
                ("defaites", models.PositiveSmallIntegerField(default=0)),
                ("buts_pour", models.PositiveSmallIntegerField(default=0)),
                ("buts_contre", models.PositiveSmallIntegerField(default=0)),
                ("difference", models.SmallIntegerField(default=0)),
                ("points", models.PositiveSmallIntegerField(default=0)),
                (
                    "forme_recente",
                    models.CharField(
                        blank=True,
                        help_text='Cinq derniers résultats, ex. "VVNDV" (le plus récent en dernier).',
                        max_length=10,
                    ),
                ),
                ("maj_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Classement de ligue",
                "verbose_name_plural": "Classements de ligue",
                "db_table": "communaute_classement_ligue",
                "ordering": ["saison", "rang"],
            },
        ),
        migrations.CreateModel(
            name="RencontreCalendrier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("evenement_externe_id", models.CharField(max_length=50, unique=True)),
                ("competition", models.CharField(blank=True, max_length=200)),
                ("equipe_domicile", models.CharField(max_length=200)),
                ("equipe_exterieur", models.CharField(max_length=200)),
                ("date_heure", models.DateTimeField()),
                ("score_domicile", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("score_exterieur", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("maj_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rencontre au calendrier",
                "verbose_name_plural": "Calendrier des rencontres",
                "db_table": "communaute_calendrier_rencontres",
                "ordering": ["date_heure"],
                "indexes": [
                    models.Index(fields=["date_heure"], name="communaute__date_he_ba3122_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchEvenement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("coup_envoi", "Coup d'envoi"),
                            ("but", "But"),
                            ("carton_jaune", "Carton jaune"),
                            ("carton_rouge", "Carton rouge"),
                            ("remplacement", "Remplacement"),
                            ("mi_temps", "Mi-temps"),
                            ("fin_match", "Fin du match"),
                        ],
                        max_length=20,
                    ),
                ),
                ("minute", models.PositiveSmallIntegerField()),
                (
                    "equipe",
                    models.CharField(
                        blank=True,
                        choices=[("ca", "Club Africain"), ("adversaire", "Adversaire")],
                        max_length=10,
                    ),
                ),
                ("joueur", models.CharField(blank=True, max_length=200)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_evenements_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements",
                        to="communaute.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement de match",
                "verbose_name_plural": "Événements de match",
                "db_table": "communaute_match_evenements",
                "ordering": ["minute", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="classementligue",
            constraint=models.UniqueConstraint(
                fields=("saison", "equipe"), name="classement_saison_equipe_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="matchevenement",
            index=models.Index(fields=["match", "minute"], name="communaute__match_i_de2450_idx"),
        ),
    ]
