# Generated by Django 4.2.16 on 2026-09-24 20:23
#
# Module Tippspiel (pronostics Ligue 1) — voir docstring de tête models.py, section
# "Tippspiel (pronostics Ligue 1)" pour le contexte complet (retour utilisateur du
# 2026-09-24, décisions AskUserQuestion : périmètre limité aux rencontres Ligue 1 de
# Club Africain déjà synchronisées, système de paiement autonome sans réutilisation de
# apps.cotisations).

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0004_historique_statut_membre"),
        ("boutique", "0006_produit_type_produit_alter_bonachat_statut_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communaute", "0010_migrer_vers_goal_api_donnees"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tippspiel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("saison", models.CharField(help_text='Ex. "2026-2027".', max_length=20)),
                (
                    "regles",
                    models.TextField(
                        blank=True,
                        help_text="Affiché aux membres comme rappel du barème de points.",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("publie", "Publié"),
                            ("cloture", "Clôturé"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                (
                    "montant_participation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vide = jeu gratuit.",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("maj_le", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tippspiele_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tippspiel",
                "verbose_name_plural": "Tippspiele",
                "db_table": "communaute_tippspiele",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TippspielTeilnahme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "statut_paiement",
                    models.CharField(
                        choices=[
                            ("sans_frais", "Sans frais"),
                            ("en_attente", "En attente de paiement"),
                            ("confirmee", "Paiement confirmé"),
                        ],
                        default="sans_frais",
                        max_length=20,
                    ),
                ),
                ("confirmee_le", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tippspiel_paiements_confirmes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tippspiel_participations",
                        to="membres.membre",
                    ),
                ),
                (
                    "tippspiel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="communaute.tippspiel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation Tippspiel",
                "verbose_name_plural": "Participations Tippspiel",
                "db_table": "communaute_tippspiel_teilnahmen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TippspielTip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("score_domicile", models.PositiveSmallIntegerField()),
                ("score_exterieur", models.PositiveSmallIntegerField()),
                ("points", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("maj_le", models.DateTimeField(auto_now=True)),
                (
                    "rencontre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tippspiel_tipps",
                        to="communaute.rencontrecalendrier",
                    ),
                ),
                (
                    "teilnahme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipps",
                        to="communaute.tippspielteilnahme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pronostic Tippspiel",
                "verbose_name_plural": "Pronostics Tippspiel",
                "db_table": "communaute_tippspiel_tipps",
                "ordering": ["rencontre__date_heure"],
            },
        ),
        migrations.CreateModel(
            name="TippspielPrix",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("platz", models.PositiveSmallIntegerField(help_text="1 = première place, etc.")),
                (
                    "type_prix",
                    models.CharField(
                        choices=[
                            ("produit", "Article boutique"),
                            ("montant_fixe", "Montant fixe"),
                            ("pourcentage", "Pourcentage de la cagnotte"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Renseigné uniquement si type_prix=montant_fixe.",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "pourcentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Renseigné uniquement si type_prix=pourcentage (0-100).",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Renseigné uniquement si type_prix=produit.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="boutique.produit",
                    ),
                ),
                (
                    "tippspiel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prix",
                        to="communaute.tippspiel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot Tippspiel",
                "verbose_name_plural": "Lots Tippspiel",
                "db_table": "communaute_tippspiel_prix",
                "ordering": ["tippspiel", "platz"],
            },
        ),
        migrations.AddConstraint(
            model_name="tippspieltip",
            constraint=models.UniqueConstraint(
                fields=("teilnahme", "rencontre"), name="tippspiel_tip_rencontre_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="tippspielteilnahme",
            constraint=models.UniqueConstraint(
                fields=("tippspiel", "membre"), name="tippspiel_teilnahme_membre_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="tippspielprix",
            constraint=models.UniqueConstraint(
                fields=("tippspiel", "platz"), name="tippspiel_prix_rang_unique"
            ),
        ),
    ]
