# Generated by Django 4.2.16 on 2026-09-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communaute", "0011_ajoute_module_tippspiel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipeInfo",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=200)),
                ("logo_url", models.URLField(blank=True, max_length=500)),
                ("fondee_en", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("stade", models.CharField(blank=True, max_length=200)),
                ("ville", models.CharField(blank=True, max_length=200)),
                ("pays", models.CharField(blank=True, max_length=100)),
                ("entraineur", models.CharField(blank=True, max_length=200)),
                (
                    "donnees_brutes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=(
                            "Réponse GOAL API brute (`GET /teams/{id}`) telle quelle — filet "
                            "de sécurité en cas de mapping de champ incorrect, voir docstring "
                            "de classe."
                        ),
                    ),
                ),
                ("maj_le", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Informations équipe",
                "verbose_name_plural": "Informations équipe",
                "db_table": "communaute_equipe_info",
            },
        ),
    ]
