# Generated by Django 4.2.16 on 2026-09-25 11:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0004_historique_statut_membre"),
        ("communaute", "0012_ajoute_equipe_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagegroupe",
            name="repond_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reponses",
                to="communaute.messagegroupe",
            ),
        ),
        migrations.AddField(
            model_name="messageprive",
            name="repond_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reponses",
                to="communaute.messageprive",
            ),
        ),
        migrations.CreateModel(
            name="MessagePriveLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_messages_prives",
                        to="membres.membre",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="communaute.messageprive",
                    ),
                ),
            ],
            options={
                "db_table": "communaute_message_prive_likes",
            },
        ),
        migrations.CreateModel(
            name="MessageGroupeLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_messages_groupe",
                        to="membres.membre",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="communaute.messagegroupe",
                    ),
                ),
            ],
            options={
                "db_table": "communaute_message_groupe_likes",
            },
        ),
        migrations.AddConstraint(
            model_name="messageprivelike",
            constraint=models.UniqueConstraint(
                fields=("message", "membre"), name="un_seul_like_message_prive_par_membre"
            ),
        ),
        migrations.AddConstraint(
            model_name="messagegroupelike",
            constraint=models.UniqueConstraint(
                fields=("message", "membre"), name="un_seul_like_message_groupe_par_membre"
            ),
        ),
    ]
