# Generated by Django 4.2.16 on 2026-09-27 11:23

import apps.communaute.models
import apps.communaute.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0004_historique_statut_membre"),
        ("communaute", "0013_ajoute_reponse_et_like_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationSitePublic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "video_hero",
                    models.FileField(
                        blank=True,
                        help_text="Vidéo de fond du hero de la page d'accueil publique (MP4, silencieuse).",
                        null=True,
                        storage=apps.communaute.storage.PublicationsStorage(),
                        upload_to=apps.communaute.models.video_hero_upload_path,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bureau Admin+ ayant modifié ce paramétrage en dernier.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration du site public",
                "verbose_name_plural": "Configuration du site public",
                "db_table": "communaute_configuration_site_public",
            },
        ),
    ]
