# Generated by Django 4.2.16 on 2026-09-28 14:26

import apps.communaute.models
import apps.communaute.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0004_historique_statut_membre"),
        ("communaute", "0014_configurationsitepublic"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipeLogo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("equipe", models.CharField(max_length=200, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        storage=apps.communaute.storage.PublicationsStorage(),
                        upload_to=apps.communaute.models.equipe_logo_upload_path,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bureau Admin+ ayant téléversé/remplacé ce logo en dernier.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logo d'équipe (Fan-Club)",
                "verbose_name_plural": "Logos d'équipes (Fan-Club)",
                "db_table": "communaute_equipe_logo",
                "ordering": ["equipe"],
            },
        ),
    ]
