# Generated by Django 4.2.16 on 2026-09-29 12:45

import apps.communaute.models
import apps.communaute.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0006_alter_membre_photo"),
        ("communaute", "0015_equipelogo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArrierePlanModule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("module", models.CharField(max_length=50, unique=True)),
                (
                    "image",
                    models.ImageField(
                        storage=apps.communaute.storage.PublicationsStorage(),
                        upload_to=apps.communaute.models.arriere_plan_module_upload_path,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modifie_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bureau Admin+ ayant téléversé/remplacé cette image en dernier.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image de fond par module",
                "verbose_name_plural": "Images de fond par module",
                "db_table": "communaute_arriere_plan_module",
                "ordering": ["module"],
            },
        ),
    ]
