# Generated by Django 4.2.16 on 2026-10-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communaute", "0016_arriereplanmodule"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="important",
            field=models.BooleanField(default=False),
        ),
    ]
