# Generated by Django 4.2.16 on 2026-10-05 19:52

import apps.communaute.models
import apps.communaute.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communaute", "0017_publication_important"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationsitepublic",
            name="kachel1_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configurationsitepublic",
            name="kachel1_largeur",
            field=models.CharField(
                choices=[("pleine", "Pleine largeur"), ("demi", "Demi-largeur")],
                default="demi",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="configurationsitepublic",
            name="kachel1_lien",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="configurationsitepublic",
            name="kachel1_media",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.communaute.storage.PublicationsStorage(),
                upload_to=apps.communaute.models.kachel_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="configurationsitepublic",
            name="kachel1_texte",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="configurationsitepublic",
            name="kachel1_titre",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="configurationsitepublic",
            name="kachel2_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="configurationsitepublic",
            name="kachel2_largeur",
            field=models.CharField(
                choices=[("pleine", "Pleine largeur"), ("demi", "Demi-largeur")],
                default="demi",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="configurationsitepublic",
            name="kachel2_lien",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="configurationsitepublic",
            name="kachel2_media",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.communaute.storage.PublicationsStorage(),
                upload_to=apps.communaute.models.kachel_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="configurationsitepublic",
            name="kachel2_texte",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="configurationsitepublic",
            name="kachel2_titre",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
