# Generated by Django 4.2.16 on 2026-09-22 17:02

import apps.projets.models
import apps.projets.storage
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membres", "0004_historique_statut_membre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description_html", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_preparation", "En préparation"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="en_preparation",
                        max_length=20,
                    ),
                ),
                (
                    "cagnote_active",
                    models.BooleanField(
                        default=False,
                        help_text="Autorise les membres à verser une contribution libre à ce projet.",
                        verbose_name="Contributions libres activées",
                    ),
                ),
                (
                    "objectif_montant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optionnel — la barre de progression reste masquée si vide.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Objectif de la cagnote",
                    ),
                ),
                (
                    "date_limite",
                    models.DateField(blank=True, null=True, verbose_name="Date limite"),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projets_crees",
                        to="membres.membre",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projets_geres",
                        to="membres.membre",
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet / Action",
                "verbose_name_plural": "Projets / Actions",
                "db_table": "projets_projets",
                "ordering": ["ordre", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjetMiseAJour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu_html", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membres.membre",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mises_a_jour",
                        to="projets.projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mise à jour de projet",
                "verbose_name_plural": "Mises à jour de projet",
                "db_table": "projets_mises_a_jour",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjetMiseAJourImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=apps.projets.storage.ProjetsStorage(),
                        upload_to=apps.projets.models.mise_a_jour_image_upload_path,
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mise_a_jour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projets.projetmiseajour",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image de mise à jour",
                "verbose_name_plural": "Images de mise à jour",
                "db_table": "projets_mises_a_jour_images",
                "ordering": ["ordre", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjetImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=apps.projets.storage.ProjetsStorage(),
                        upload_to=apps.projets.models.projet_image_upload_path,
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projets.projet",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image de projet",
                "verbose_name_plural": "Images de projet",
                "db_table": "projets_images",
                "ordering": ["ordre", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="projet",
            index=models.Index(fields=["statut"], name="projets_pro_statut_28ba68_idx"),
        ),
    ]
