# Generated by Django 4.2.16 on 2026-09-11 09:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cotisations", "0001_initial"),
        ("membres", "0003_membre_pays_alter_membre_adresse_de_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampagneAdhesion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("annee", models.PositiveSmallIntegerField()),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("publiee", "Publiée"),
                            ("cloturee", "Clôturée"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Membre du Bureau ayant créé la campagne (traçabilité — SCD §7).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campagnes_creees",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campagne d'adhésion",
                "verbose_name_plural": "Campagnes d'adhésion",
                "db_table": "adhesions_campagnes",
                "ordering": ["-annee", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OffreAdhesion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "prix_plein",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "avantages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Liste ordonnée d\'avantages trilingues : [{"ordre": 1, "texte_fr": "...", "texte_de": "...", "texte_ar": "..."}, ...].',
                    ),
                ),
                ("condition_age_min", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("condition_age_max", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "visible",
                    models.BooleanField(
                        default=True,
                        help_text="Décoché : offre gardée au catalogue mais masquée côté membre.",
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                (
                    "campagne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offres",
                        to="adhesions.campagneadhesion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre d'adhésion",
                "verbose_name_plural": "Offres d'adhésion",
                "db_table": "adhesions_offres",
                "ordering": ["campagne", "ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="RabaisOffre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type_rabais",
                    models.CharField(
                        choices=[
                            ("etudiant", "Étudiant"),
                            ("famille", "Famille"),
                            ("senior", "Senior"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label_fr", models.CharField(max_length=200)),
                ("label_de", models.CharField(blank=True, max_length=200)),
                ("label_ar", models.CharField(blank=True, max_length=200)),
                (
                    "montant_reduction",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "pct_reduction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("justificatif_requis", models.BooleanField(default=False)),
                ("instructions_fr", models.TextField(blank=True)),
                ("instructions_de", models.TextField(blank=True)),
                ("instructions_ar", models.TextField(blank=True)),
                (
                    "offre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rabais",
                        to="adhesions.offreadhesion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rabais",
                "verbose_name_plural": "Rabais",
                "db_table": "adhesions_rabais",
                "ordering": ["offre", "type_rabais"],
            },
        ),
        migrations.CreateModel(
            name="Souscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date_souscription", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "prix_paye",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("en_attente_justificatif", "En attente de justificatif"),
                            ("en_attente_paiement", "En attente de paiement"),
                            ("payee", "Payée"),
                            ("rabais_refuse", "Rabais refusé"),
                            ("annulee", "Annulée"),
                            ("expiree", "Expirée"),
                        ],
                        default="brouillon",
                        max_length=30,
                    ),
                ),
                (
                    "snapshot_avantages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Copie immuable de OffreAdhesion.avantages au moment de la souscription — l'historique d'un membre ne doit jamais changer rétroactivement si l'offre évolue.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campagne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="souscriptions",
                        to="adhesions.campagneadhesion",
                    ),
                ),
                (
                    "cotisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Écriture de paiement liée, une fois la souscription payée.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="souscription_adhesion",
                        to="cotisations.cotisation",
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="souscriptions",
                        to="membres.membre",
                    ),
                ),
                (
                    "offre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="souscriptions",
                        to="adhesions.offreadhesion",
                    ),
                ),
                (
                    "rabais",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="souscriptions",
                        to="adhesions.rabaisoffre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Souscription",
                "verbose_name_plural": "Souscriptions",
                "db_table": "adhesions_souscriptions",
                "ordering": ["-date_souscription"],
                "indexes": [
                    models.Index(
                        fields=["membre", "campagne"], name="adhesions_s_membre__078e4e_idx"
                    ),
                    models.Index(fields=["statut"], name="adhesions_s_statut_e3bbea_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="souscription",
            constraint=models.UniqueConstraint(
                fields=("membre", "campagne"), name="une_seule_souscription_par_membre_et_campagne"
            ),
        ),
        migrations.AddConstraint(
            model_name="rabaisoffre",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("montant_reduction__isnull", False), ("pct_reduction__isnull", True)),
                    models.Q(("montant_reduction__isnull", True), ("pct_reduction__isnull", False)),
                    _connector="OR",
                ),
                name="rabais_montant_xor_pourcentage",
            ),
        ),
        migrations.AddIndex(
            model_name="offreadhesion",
            index=models.Index(
                fields=["campagne", "visible"], name="adhesions_o_campagn_7b2102_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campagneadhesion",
            index=models.Index(fields=["annee", "statut"], name="adhesions_c_annee_09c3d7_idx"),
        ),
        migrations.AddConstraint(
            model_name="campagneadhesion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("statut", "publiee")),
                fields=("annee",),
                name="une_seule_campagne_publiee_par_annee",
            ),
        ),
    ]
