# Generated by Django 4.2.16 on 2026-09-11 12:37

import apps.adhesions.models
import apps.adhesions.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("membres", "0003_membre_pays_alter_membre_adresse_de_and_more"),
        ("adhesions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JustificatifRabais",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        storage=apps.adhesions.storage.JustificatifsStorage(),
                        upload_to=apps.adhesions.models.justificatif_upload_path,
                    ),
                ),
                ("type_justificatif", models.CharField(blank=True, max_length=100)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuve", "Approuvé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_decision", models.DateTimeField(blank=True, null=True)),
                ("motif_rejet", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "souscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="justificatif",
                        to="adhesions.souscription",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Membre du rôle RH+ ayant approuvé ou rejeté ce justificatif.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="justificatifs_valides",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Justificatif de rabais",
                "verbose_name_plural": "Justificatifs de rabais",
                "db_table": "adhesions_justificatifs",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["statut"], name="adhesions_j_statut_2848e1_idx")],
            },
        ),
    ]
