# Generated by Django 4.2.16 on 2026-09-29 07:32

import apps.adhesions.models
import apps.adhesions.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhesions", "0003_backfill_cotisation_souscriptions_en_attente"),
    ]

    operations = [
        migrations.AddField(
            model_name="offreadhesion",
            name="couleur",
            field=models.CharField(
                blank=True,
                choices=[("cat_1", "Couleur 1"), ("cat_2", "Couleur 2"), ("cat_3", "Couleur 3")],
                help_text="Surlignage de couleur de la kachel. Vide = attribution automatique.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="offreadhesion",
            name="icone",
            field=models.ImageField(
                blank=True,
                help_text="Icône affichée sur la kachel de cette offre (mycid.org/membership).",
                null=True,
                storage=apps.adhesions.storage.OffreIconeStorage(),
                upload_to=apps.adhesions.models.offre_icone_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="offreadhesion",
            name="populaire",
            field=models.BooleanField(
                default=False,
                help_text="Affiche le badge \"Beliebt\" (Populaire) sur cette offre. Si aucune offre d'une campagne n'est marquée, le badge reste placé automatiquement sur l'offre du milieu (comportement historique, voir accentOffre()/populaire côté frontend).",
            ),
        ),
    ]
