# Generated by Django 4.2.16 on 2026-10-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhesions", "0004_offreadhesion_couleur_offreadhesion_icone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campagneadhesion",
            name="bascule_non_renouveles_le",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="campagneadhesion",
            name="date_limite_renouvellement",
            field=models.DateField(
                blank=True,
                help_text="Frist für Bestandsmitglieder. Vide = aucune bascule automatique.",
                null=True,
            ),
        ),
    ]
